---
name: Lint json file
on: push
permissions: {}
jobs:
  json-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install ESLint
        run: npm install --save-dev eslint @eslint/json
      - name: Run ESLint
        run: npx eslint policies.json
